# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "jromero/static"
version = "0.0.1"
name = "Static Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"