# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "jromero/self-signed-check"
version = "0.0.1"
name = "Self-Signed Cert Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"